apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "rancher.fullname" . }}
  labels:
    {{- include "rancher.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "rancher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
