apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-pv.pvc1
  labels:
    app: test-pod-pv.pvc1

spec:
  containers:
    - name: busybox
      image: busybox:1.32
      tty: true
      volumeMounts:
        - mountPath: /data
          name: html-dir
    - name: nginx
      image: nginx:1.18.0
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html-dir

  volumes:
    - name: html-dir
      persistentVolumeClaim:
        claimName: sample-pvc1