apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-pvc2
spec:
  accessModes:          # REQUIRED
    - ReadWriteOnce
  resources:            # REQUIRED
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: nfs
      target: sample2