apiVersion: v1
kind: Service
metadata:
  name: sample-srv-cip
spec:
  #type: ClusterIP # NOT REQUIRED, AS DEFAULT
  selector:
    app: test-dep
  ports:
    - protocol: TCP
      port: 80        # REQUIRED
      targetPort: 80  # if not set, same as port