apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-vol
  labels:
    app: test-pod-vol

spec:
  containers:
    - name: busybox
      image: busybox:1.32
      tty: true
      volumeMounts:
        - mountPath: /data
          name: data-dir
    - name: nginx
      image: nginx:1.18.0
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html-dir
          readOnly: true
  volumes:
    - name: data-dir
      hostPath:
        path: /opt/test-pod
        type: DirectoryOrCreate
    - name: html-dir
      hostPath:
        path: /opt/test-pod
        type: DirectoryOrCreate