apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ngnix-ceph-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: rook-cephfs

---

apiVersion: v1
kind: Pod
metadata:
  name: ngnix-ceph-pod
  labels:
    app: ngnix-ceph-pod
spec:
  containers:
    - name: ngnix
      image: reg.local/nginx:1.18.0
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
  volumes:
    - name: html
      persistentVolumeClaim:
        claimName: ngnix-ceph-pvc
        readOnly: false

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-ceph-svc
spec:
  selector:
    app: ngnix-ceph-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
---
---

apiVersion: v1
kind: Pod
metadata:
  name: busybox-ceph-pod
spec:
  containers:
    - name: busybox
      image: reg.local/busybox:1.32
      tty: true
      volumeMounts:
        - name: date
          mountPath: /data
  volumes:
    - name: date
      persistentVolumeClaim:
        claimName: ngnix-ceph-pvc
        readOnly: false