kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-config-override
  namespace: rook-ceph # namespace:cluster
data:
  config: |
    [global]
    osd_pool_default_size = 1
    mon_warn_on_pool_no_redundancy = false

---

apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: reg.local/ceph/ceph:v15.2.10
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: true
    ssl: true
  crashCollector:
    disable: true
  storage:
    useAllNodes: true
    useAllDevices: false
    #deviceFilter: "sdb"
    #devicePathFilter: "^/dev/ceph/.*"
    devices:
      - name: sdb
      #- name: sdc
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
        timeout: 600s
