version: '3.6'

services:

  mongo:
    image: mongo:4.0.13-xenial
    ports:
      - 27017:27017
    volumes:
      - ./MongoDB:/data/db
    networks:
      - net

  oracle:
    image: store/oracle/database-enterprise:12.2.0.1
    tty: true
    ports:
      - 1521:1521
    volumes:
      - ./OracleDB:/ORCL
    networks:
      - net

  postgres:
    image: postgres:12.2
    ports:
      - 5432:5432
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./Postgres:/var/lib/postgresql/data
    networks:
      - net

  mysql8:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./Mysql8:/var/lib/mysql
    networks:
      - net

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - ./ZookeeperData:/var/lib/zookeeper/data
      - ./ZookeeperLog:/var/lib/zookeeper/log
    ports:
      - 2181:2181
    networks:
      - net

  kafka:
    image: confluentinc/cp-kafka:5.3.1-1
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      # Multi-Net Config
      # KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      # KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

      # All-Same-Net Simple Config
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    volumes:
      - ./Kafka/data:/var/lib/kafka/data
    ports:
      - 9092:9092
    networks:
      - net

  registry:
    image: registry:2.7.1
    environment:
      # REQUIRED TO DELETE IMAGES
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - ./Registry:/var/lib/registry
    ports:
      - 80:5000
    networks:
      - net

  registry_sec:
    image: registry:2.7.1
    environment:
      # REQUIRED TO DELETE IMAGES
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/reg.local.crt"
      REGISTRY_HTTP_TLS_KEY: "/certs/reg.local.key"
    volumes:
      - ./Registry:/var/lib/registry
      - ./certs:/certs
    ports:
      - 443:5000
    networks:
      - net

  jupyter:
    image: jupyter/scipy-notebook:lab-3.1.13
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ./Jupyter:/home/jovyan/work
    ports:
      - 10000:8888
    networks:
      - net

  consul:
    image: consul:1.10.2
    entrypoint: ""
    command:
      - /bin/sh
      - -c
      - |
        {
          sleep 8
          echo "----- BACKGROUND -----"
          consul acl policy create -name anonymous_read -rules 'service_prefix "" {policy = "read"}'
          consul acl token update -id 00000000-0000-0000-0000-000000000002 -policy-name anonymous_read
        } &
        docker-entrypoint.sh agent -dev
    environment:
      CONSUL_HTTP_TOKEN: "0527f6e7-ea8c-49b7-91c3-4d21be73d508"
    ports:
      - 8500:8500
      - 8600:8600/udp
    volumes:
      - ./Consul/Data:/consul/data
      - ./Consul/Config:/consul/config:ro
    networks:
      - net

networks:
  net:
    external: true
    name: mynet